export const ADD_ITEM = 'ADD_ITEM'
export const SET_EDIT_ID = 'SET_EDIT_ID'
export const SET_ITEMS = 'SET_ITEMS'
export const SET_TOGGLE_COMPLETE = 'SET_TOGGLE_COMPLETE'
export const SET_UPDATE_TEXT = 'SET_UPDATE_TEXT'
